# Generated by Django 2.2.6 on 2019-10-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.CharField(max_length=250)),
                ('Address2', models.CharField(max_length=250, null=True)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=3)),
                ('Zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CFApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestedLoanAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('StatedCreditHistory', models.IntegerField()),
                ('LegalEntityType', models.CharField(max_length=5)),
                ('FilterID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=250)),
                ('City', models.CharField(max_length=25)),
                ('State', models.CharField(max_length=10)),
                ('Zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFRequestId', models.IntegerField()),
                ('RequestDate', models.DateTimeField(auto_now_add=True)),
                ('CFApiUserId', models.CharField(blank=True, max_length=60)),
                ('CFApiPassword', models.CharField(blank=True, max_length=60)),
                ('IsTestLead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SelfReportedCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualRevenue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('MonthlyAverageBankBalance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('MonthlyAverageCreditCardVolume', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('Name', models.CharField(max_length=120)),
                ('FirstName', models.CharField(max_length=120)),
                ('LastName', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('DateOfBirth', models.DateField()),
                ('HomePhone', models.CharField(max_length=12)),
                ('SSN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PercentageOfOwnership', models.FloatField()),
                ('HomeAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HomeAddress')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('Name', models.CharField(max_length=250)),
                ('TaxID', models.IntegerField()),
                ('Phone', models.CharField(max_length=12)),
                ('NAICS', models.IntegerField(primary_key=True, serialize=False)),
                ('HasBeenProfitable', models.BooleanField()),
                ('HasBankruptedInLast7Years', models.BooleanField()),
                ('InceptionDate', models.DateTimeField(auto_now_add=True)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BusinessAddress')),
                ('SelfReportedCashFlow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SelfReportedCashFlow')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Business')),
                ('CFApplicationData', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CFApplicationData')),
                ('Owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Owner')),
                ('RequestHeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RequestHeader')),
            ],
        ),
    ]
